columnSuffix: null
contentColumnType: string
fieldGroup: 54c3ccf3-230b-400f-9cb5-cf22dc8fc937 # Blog Post Fields
handle: featureImage
instructions: ''
name: 'Feature Image '
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1b917b4f-ab49-47ad-9d59-9af2e408f825' # Blog
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1b917b4f-ab49-47ad-9d59-9af2e408f825' # Blog
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
